name: Crystal CI

on:
  release:
    types:
      - created

jobs:
  release_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
      - name: Build
        run: |
          crystal build --release --no-debug --static --progress -o bin/crupload main.cr
          strip bin/crupload
      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/crupload
          asset_name: crupload-${{ github.event.release.tag_name }}-macos
          asset_content_type: binary/octet-stream


  release_linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          crystal build --release --no-debug --static --progress -o bin/crupload main.cr
          strip bin/crupload
      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/crupload
          asset_name: crupload-${{ github.event.release.tag_name }}-linux
          asset_content_type: binary/octet-stream
  release_windows:
    runs-on: windows-latest
    steps:
      # - name: Set git to use LF instead of CRLF
      #   run: |
      #     git config --global core.autocrlf false
      #     git config --global core.eol lf
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Build
        #shell: bash
        run: crystal build --release --no-debug --static --progress -o bin/crupload.exe main.cr
      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/crupload.exe
          asset_name: crupload-${{ github.event.release.tag_name }}-windows.exe
          asset_content_type: binary/octet-stream
