name: Matrix Release

# on:
#   release:
#     types:
#       - created

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest}
          - {os: macos-latest}
          # Crystal 1.4.1 isn't supported on Windows, and 1.5.0-dev build fails.
          # Will wait for official 1.5.0 release, the team seems to be working on the causing issues.
          - {os: windows-latest, extension: .exe}
    runs-on: ${{matrix.os}}
    steps:
      - name: Download source
        uses: actions/checkout@v2

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.5.0

      - name: Install shards
        run: shards install

      - name: Build
        run: |
          shards build --release --no-debug --progress
          if [ -e bin/crupload.exe ]; then mv bin/crupload.exe bin/crupload; fi
          strip bin/crupload

      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: ./bin/crupload
          asset_name: crupload-${{github.event.release.tag_name}}-${{matrix.os}}${{matrix.extension}}
          asset_content_type: binary/octet-stream
